module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface": "#131313",
              "outline": "#8e9192",
              "secondary-fixed-dim": "#c6c7bf",
              "tertiary-fixed": "#e4e2e1",
              "background": "#131313",
              "surface-container-low": "#1b1b1b",
              "on-background": "#e2e2e2",
              "surface-container-lowest": "#0e0e0e",
              "tertiary": "#ffffff",
              "error-container": "#93000a",
              "secondary-fixed": "#e2e3da",
              "primary-fixed": "#e2e2e2",
              "on-secondary-fixed": "#1a1c17",
              "surface-container-highest": "#353535",
              "smoke": "#F5F5F7",
              "surface-variant": "#353535",
              "error": "#ffb4ab",
              "surface-container-high": "#2a2a2a",
              "inverse-primary": "#5d5f5f",
              "on-primary-fixed": "#1a1c1c",
              "on-surface-variant": "#c4c7c8",
              "onyx-grey": "#222222",
              "inverse-on-surface": "#303030",
              "on-secondary-container": "#b4b6ae",
              "surface-container": "#1f1f1f",
              "primary-container": "#e2e2e2",
              "secondary-container": "#454841",
              "on-secondary-fixed-variant": "#454841",
              "on-error": "#690005",
              "primary": "#ffffff",
              "on-tertiary-fixed-variant": "#474746",
              "on-primary-container": "#636565",
              "on-tertiary-container": "#656464",
              "primary-fixed-dim": "#c6c6c7",
              "inverse-surface": "#e2e2e2",
              "on-secondary": "#2f312b",
              "muted-silver": "#8C8C8C",
              "tertiary-container": "#e4e2e1",
              "surface-tint": "#c6c6c7",
              "on-primary": "#2f3131",
              "on-primary-fixed-variant": "#454747",
              "on-tertiary-fixed": "#1b1c1c",
              "on-error-container": "#ffdad6",
              "on-surface": "#e2e2e2",
              "surface-dim": "#131313",
              "on-tertiary": "#303030",
              "surface-bright": "#393939",
              "secondary": "#c6c7bf",
              "outline-variant": "#444748",
              "tertiary-fixed-dim": "#c8c6c5"
          },
          "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
          },
          "spacing": {
              "section-gap": "160px",
              "unit": "8px",
              "margin-desktop": "80px",
              "gutter": "24px",
              "margin-mobile": "20px",
              "container-max": "1440px"
          },
          "fontFamily": {
              "display-hero-mobile": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "body-md": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "headline-lg": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "headline-md": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "button": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "label-caps": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "display-hero": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"],
              "body-lg": ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Helvetica", "Arial", "sans-serif"]
          },
          "fontSize": {
              "display-hero-mobile": ["32px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
              "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500"}],
              "headline-md": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}],
              "button": ["15px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}],
              "display-hero": ["74px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "500"}],
              "body-lg": ["20px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
